// spell-checker:ignore () commitLint
module.exports = {
	extends: ['@commitlint/config-conventional'],
	parserPreset: './.commitlint.parser-preset.js',
	plugins: [
		{
			rules: {
				'@local/DEBUG': (parsed, when, value) => {
					return [true, console.log({ parsed, when, value })];
				},
			},
		},
	],
	rules: {
		// '@local/DEBUG': [1, 'always'],
		'body-max-line-length': [0],
		'scope-case': [2, 'always', ['lower-case', 'upper-case']],
		'subject-case': [0],
		'type-case': [2, 'always', ['lower-case', 'sentence-case']],
		'type-enum': [
			2,
			'always',
			[
				'add',
				'added',
				'bugfix',
				'build',
				'change',
				'changed',
				'chore',
				'docs',
				'feat',
				'fix',
				'fixed',
				'fixes',
				'maint',
				'merge',
				'perf',
				'refactor',
				'revert',
				'style',
				'test',
				'tests',
				'update',
				'updated',
				'upkeep',
				'wip',
				'Add',
				'Added',
				'Bugfix',
				'Build',
				'Change',
				'Changed',
				'Chore',
				'Docs',
				'Feat',
				'Fix',
				'Fixed',
				'Fixes',
				'Maint',
				'Merge',
				'Perf',
				'Refactor',
				'Revert',
				'Style',
				'Test',
				'Tests',
				'Update',
				'Updated',
				'Upkeep',
				'WIP',
			],
		],
	},
};
